# Generated by Django 2.1.1 on 2019-04-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ronbun',
            field=models.URLField(blank=True, null=True, verbose_name='論文'),
        ),
    ]
